import { useContext, useEffect } from "react";
import axios from 'axios';
import { LoginContext, LoginProvider } from "../context";
import Head from "next/head";


import Section from '../Elements/Section'
import Row from '../Elements/Row'
import Col from '../Elements/Column'
import MainNav from '../components/MainNav'
import Login from '../components/Login'


import '../node_modules/bootstrap/dist/css/bootstrap.min.css'
import '../styles/globals.css'
import '../styles/style.scss'


import type { AppProps } from 'next/app'
import { Value } from "sass";

// axios.defaults.baseURL = 'http://localhost:3000';


function MyApp({ Component, pageProps }: AppProps) {
  const login = useContext(LoginContext);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossOrigin="anonymous"></script>
      </Head>
      <div className="bdy">
        <LoginProvider>
          <Section id='ex-top' className='ex-top no-padding' container='fixed'>
            <Row id='ex-row-top' className='align-items-center'>
              <Col className='col-2'>
                <h1>Pakhi Bhai</h1>
              </Col>
              <Col className='col-7'> 
                <MainNav />
              </Col>
              <Col className='col-3'>
                <Login />
              </Col>
            </Row>
          </Section>
        
          <Component {...pageProps} />

        </LoginProvider>
      </div>
    </>
  )
}

export default MyApp
